NutriSoftwareV2/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using NutriSoftware.Negocio.Domain;
using NutriSoftware.Negocio.Svc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NutriSoftwareV2.Web.Controllers
{
    public class PacienteController : Controller
    {
        public ActionResult Index(int? Id)
        {
            List<Paciente> pacientes = SvcPaciente.ListarPacientes();
            if (Id.HasValue)
            {
                ViewBag.Paciente = SvcPaciente.BuscarPacienteCompleto(Id.Value);
            }
            return View(pacientes);
        }

        [HttpPost]
        public ActionResult PesquisaPaciente(string pesquisaPaciente)
        {
            var pesquisa = SvcPaciente.PesquisarPaciente(pesquisaPaciente);
            return PartialView("PartiaisPaciente/_ListaDePacientes", pesquisa);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView("PartiaisPaciente/_FormularioPaciente");
        }

        [HttpPost]
        public ActionResult Create(Paciente paciente)
        {
            try
            {
                if (paciente != null)
                {
                    SvcPaciente.CadastrarPaciente(paciente);
                    ViewBag.Paciente = paciente;
                    var pacientes = SvcPaciente.ListarPacientes();
                    return PartialView("PartiaisPaciente/_Conteudo", pacientes);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var paciente = SvcPaciente.BuscarPacienteCompleto(id);
            return PartialView("PartiaisPaciente/_FormularioPaciente", paciente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Paciente paciente)
        {
            try
            {
                if (paciente != null)
                {
                    SvcPaciente.AtualizarPaciente(paciente);
                    ViewBag.Paciente = paciente;
                    var pacientes = SvcPaciente.ListarPacientes();
                    return PartialView("PartiaisPaciente/_Conteudo", pacientes);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            try
            {
                SvcPaciente.DeletarPaciente(Id);
                var pacientes = SvcPaciente.ListarPacientes();
                return PartialView("PartiaisPaciente/_Conteudo", pacientes);
            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult CadastrarAnotacoesPaciente(int pacienteId)
        {
            ViewBag.IdPaciente = pacienteId;
            var anotacao = new AnotacoesPaciente { PacienteId = pacienteId, Data = DateTime.Now };
            return PartialView("PartiaisPaciente/_FormularioObservacaoPaciente", anotacao);
        }

        [HttpPost]
        public ActionResult CadastrarAnotacoesPaciente(AnotacoesPaciente anotacao)
        {
            SvcAnotacoes.CadastrarAnotacao(anotacao);
            var anotacoes = SvcAnotacoes.ListarAnotacoesPaciente(anotacao.PacienteId);
            return PartialView("PartiaisPaciente/_ObservacaoPaciente", anotacoes.OrderByDescending(d => d.Id));
        }

        [HttpGet]
        public ActionResult EditarAnotacoesPaciente(int anotacaoId)
        {
            var anotacao = SvcAnotacoes.BuscarAnotacao(anotacaoId);
            return PartialView("PartiaisPaciente/_FormularioObservacaoPaciente", anotacao);
        }

        [HttpPost]
        public ActionResult EditarAnotacoesPaciente(AnotacoesPaciente anotacao)
        {
            SvcAnotacoes.EditarAnotacao(anotacao);
            var anotacoes = SvcAnotacoes.ListarAnotacoesPaciente(anotacao.PacienteId);
            return PartialView("PartiaisPaciente/_ObservacaoPaciente", anotacoes.OrderByDescending(d => d.Id));
        }

        [HttpPost]
        public ActionResult DeletarAnotacao(int anotacaoId)
        {
            var anotacao = SvcAnotacoes.BuscarAnotacao(anotacaoId);
            int pacienteId = anotacao.PacienteId;
            SvcAnotacoes.DeletarAnotacao(anotacao);
            var anotacoes = SvcAnotacoes.ListarAnotacoesPaciente(pacienteId);
            return PartialView("PartiaisPaciente/_ObservacaoPaciente", anotacoes.OrderByDescending(p => p.Id));
        }
    }
}

NutriSoftwareV2/Views/Shared/_AlimentoJS.cshtml
<script src="~/js/alimento.js"></script>

NutriSoftwareV2/Views/Shared/_ConsultasJs.cshtml
<script src="~/js/consulta.js"></script>

NutriSoftwareV2/Views/Shared/_DietaJs.cshtml
<script src="~/js/dieta.js"></script>

NutriSoftwareV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NutriVV2.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/SwithAlerts/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/toastr/build/toastr.min.css" />
    <link rel="stylesheet" href="~/jquery-ui-1.13.2.custom/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NutriVV2.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container">
            &copy; 2022 - NutriVV2.Web - <a asp-area="" asp-controller="Paciente" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/SwithAlerts/sweetalert2.min.js"></script>
    <script src="~/toastr/build/toastr.min.js"></script>
    <script src="~/js/jQuery-Mask/dist/jquery.mask.min.js" asp-append-version="true"></script>
    <script src="~/jquery-ui-1.13.2.custom/jquery-ui.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NutriSoftwareV2/Views/Shared/_PacienteJS.cshtml
<script src="~/js/paciente.js"></script>